//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoListas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int Id { get; set; }
        public int IdCategoría { get; set; }
        public string Nombre { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
